Auth and chart
AhmadMaree/todoapp-hooks pull request #2
Opened 2020-10-24 09:21 UTC by AhmadMaree

Add use context for both Pages

2020-10-25 14:22 UTC, HinnHabib requested changes

2020-10-25 14:22 UTC, HinnHabib commented on debug.log
> +[1022/112213.383:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
This should be moved to gitignore 
No need to push

2020-10-25 14:22 UTC, HinnHabib commented on src/container/Authenticate/Auth.js
> +            </Formik>
Lets use formik hooks

2020-10-25 14:22 UTC, HinnHabib commented on src/container/Todo/Todo.js
> +          axios.put(`/ListTodo/${item.id}.json?auth=`+stateAuth.idToken,updateChecked)
Can we apply the concept of interceptor for the authentication

2020-10-25 14:22 UTC, HinnHabib commented on src/container/Todo/Todo.js
> +          axios.put(`/ListTodo/${item.id}.json?auth=`+stateAuth.idToken,updateChecked)
Will go over tomorrow

2020-10-26 07:36 UTC, AhmadMaree commented on src/container/Authenticate/Auth.js
> +            </Formik>
Done

2020-10-27 10:29 UTC, closed without merging